services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rocketseat
      RABBITMQ_DEFAULT_PASS: rocketseat
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  jaeger:
    image: jaegertracing/jaeger:2.6.0
    ports:
      - "16686:16686"
      - "14250:14250"
      - "6831:6831/udp"
      - "6832:6832/udp"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.127.0
    ports:
      - "4317:4317" # grpc
      - "4318:4318" # http
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    depends_on:
      - jaeger

  api-gateway:
    image: kong:3.9
    ports:
      - "8000:8000"  # Public API
      - "8001:8001"  # Admin API
      - "8002:8002"  # Admin GUI
      - "8443:8443"  # Public API (HTTPS)
      - "8444:8444"  # Admin API (HTTPS)
    environment:
      KONG_DATABASE: off
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DECLARATIVE_CONFIG: /kong/config.yaml
    volumes:
      - ./kong-config.yaml:/kong/config.yaml

volumes:
  rabbitmq_data:

networks:
  default:
    external:
      name: rocketseat-microservices