_format_version: "3.0"
_transform: true

services:
  - name: orders-api
    url: http://api:8080
    protocol: http
    port: 8080
    host: api
    path: /
    routes:
      - name: orders-api
        protocols:
          - http
          - https
        paths:
          - /orders-api

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - "Content-Type"
